const produtos = [
    // Ternos
    { id: 1, nome: "Terno Slim Fit Liso Castanho Claro", estoque: 12, categoria: "terno", valor: 7499.90 },
    { id: 2, nome: "Terno Slim Fit Listrado Azul escuro", estoque: 0, categoria: "terno", valor: 7999.90 },
    { id: 3, nome: "Terno Slim Fit Liso cinza", estoque: 8, categoria: "terno", valor: 7499.90 }, 
    { id: 4, nome: "Terno Slim Fit Liso Azul escuro", estoque: 0, categoria: "terno", valor: 7499.90 }, 
    { id: 5, nome: "Terno Slim Fit Risca de giz Azul escuro", estoque: 5, categoria: "terno", valor: 8299.90 },
    { id: 6, nome: "Terno Regular Fit Bege claro", estoque: 18, categoria: "terno", valor: 6999.90 },
    { id: 7, nome: "Terno Mistura de lã elástica Preto", estoque: 0, categoria: "terno", valor: 8999.90 },
    { id: 8, nome: "Terno Regular Fit Tecido elastico Azul escuro", estoque: 7, categoria: "terno", valor: 6999.90 }, 
    { id: 9, nome: "Terno Slim Fit Xadrez Azul escuro", estoque: 21, categoria: "terno", valor: 8499.90 },
    { id: 10, nome: "Terno Slim Fit Estampa Preto", estoque: 3, categoria: "terno", valor: 8799.90 },
    // Carteiras
    { id: 11, nome: "Carteira Couro vegetal Ferrugem", estoque: 0, categoria: "carteira", valor: 899.90 },
    { id: 12, nome: "Carteira Couro vegetal Marrom escuro", estoque: 30, categoria: "carteira", valor: 899.90 }, 
    { id: 13, nome: "Carteira Couro vegetal Preto", estoque: 15, categoria: "carteira", valor: 899.90 }, 
    { id: 14, nome: "Carteira Couro italiano Fivela de pino", estoque: 0, categoria: "carteira", valor: 1199.90 },
    { id: 15, nome: "Carteira Couro italiano Granulado Fivela polida Preto", estoque: 9, categoria: "carteira", valor: 1299.90 },
    { id: 16, nome: "Carteira Couro italiano Invernizado Preto", estoque: 2, categoria: "carteira", valor: 1399.90 },
    { id: 17, nome: "Carteira Couro italiano Granulado Fivela cromado", estoque: 0, categoria: "carteira", valor: 1299.90 }, 
    { id: 18, nome: "Carteira Couro italiano logotipo marcado Preto", estoque: 6, categoria: "carteira", valor: 1499.90 },
    { id: 19, nome: "Carteira Couro Italiano Escovado Preto", estoque: 1, categoria: "carteira", valor: 1499.90 }, 
    { id: 20, nome: "Carteira Couro Estampado Pino de metal Escovado", estoque: 0, categoria: "carteira", valor: 1599.90 },
    // Sapatos Sociais
    { id: 21, nome: "Sapato Oxford Couro Preto", estoque: 11, categoria: "sapato", valor: 2999.90 },
    { id: 22, nome: "Sapato Derby Couro Preto", estoque: 0, categoria: "sapato", valor: 2899.90 },
    { id: 23, nome: "Sapato Mouge Couro Fivela rolo Preto", estoque: 8, categoria: "sapato", valor: 3199.90 },
    { id: 24, nome: "Sapato Derby Couro Napa Castanho escuro", estoque: 2, categoria: "sapato", valor: 2899.90 }, 
    { id: 25, nome: "Sapato Derby Couro Sola Emborrachada Preto", estoque: 0, categoria: "sapato", valor: 2699.90 },
    { id: 26, nome: "Sapato Derby Couro Sola Emborrachada Marrom", estoque: 13, categoria: "sapato", valor: 2699.90 }, 
    { id: 27, nome: "Sapato Derby Couro Sola Biqueira Emborrachada Preto", estoque: 0, categoria: "sapato", valor: 2799.90 },
    { id: 28, nome: "Sapato Derby Couro Sola Biqueira Emborrachada Preto polido", estoque: 4, categoria: "sapato", valor: 2799.90 },
    { id: 29, nome: "Sapato Derby Couro Sola Marrom", estoque: 0, categoria: "sapato", valor: 2599.90 },
    { id: 30, nome: "Sapato Derby Couro Detalhe Brogue", estoque: 17, categoria: "sapato", valor: 3199.90 },
];

